### PR TITLE
Version UP

### PR DESCRIPTION
**Pull request by OndrejIT**

### CODE REVIEW

**Review by oliver-la — CHANGES_REQUESTED** [review]
Please move 6.3.4 to a different PR

**Comment by oliver-la** [comment]
Additionally, give the commits and PRs clear titles. (at least the seafile version, changelog preferred too)

Thanks.

**Comment by ghost** [comment]
Hello, can you update your version. Seems to be ready for Seafile server pro 6.3.6 Thanks

**Comment by oliver-la** [comment]
@NOnooSS This PR still has issues and won't be merged. Feel free to create a new PR for 6.3.6 though, I'll merge it when it meets these criterias:

- Has been tested
- Includes a changelog
- Proper title

**Comment by OndrejIT** [comment]
I tested every change, i use this docker image in production.

**Pull request closed without merging**
